# Generated by Django 4.2.11 on 2025-03-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis_apiinfo',
            name='additional_info',
            field=models.TextField(default=False),
        ),
    ]
