# Generated by Django 4.2.20 on 2025-03-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_apis_apiinfo_sample_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apis_apiinfo',
            new_name='APIINFO',
        ),
    ]
