# Generated by Django 4.2.11 on 2025-03-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_apis_apiinfo_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apis_apiinfo',
            name='sample_data',
        ),
    ]
